#!/bin/bash
####################################################################
# Prey Network Module Lang File - by Juan C. Mardones (http://juanmardones.com)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_GET_IP=" -- Getting public IP address..."
STRING_GET_LAN_IP=" -- Getting private LAN IP address..."
STRING_GET_WIFI=" -- Getting Wifi info..."
STRING_TRACE=" -- Tracing our complete route to the Internet..."
STRING_CONNECT_SSH=" -- Connecting to SSH server..."
STRING_CONNECT_SSH_Y=" -- SSH: Connecting to server now"
STRING_CONNECT_SSH_N=" -- SSH: Already connected to server"