#!/bin/bash
####################################################################
# Prey Network Module Core Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_public_ip() {
	public_ip=$(getter --connect-timeout 3 checkip.dyndns.org | sed 's/[^0-9\.]//g')
}

# for linux and mac
trace_route() {
	traceroute=$(which traceroute)
	if [ -n "$traceroute" ]; then
		complete_trace=$($traceroute -q1 www.google.com 2>&1 | grep -v -e "^[a-z]" -e "^$")
	fi
}

connect_to_ssh() {
    # these vars will come from the server/xml
    remoteport=""
    localport=""
    sshhost=""
    localhost=""
    sshusr=""
    sshcmd="ssh -fnNq -R $remoteport:$localhost:$localport $sshusr@$sshhost"
    if [[ -z $(pgrep -f "$sshcmd") ]]; then
        # only set up a connection if it hasn't already been set up
        log "$STRING_CONNECT_SSH_Y"
        # put everything in /dev/null
        eval "nohup $sshcmd &> /dev/null &"
    else
        log "$STRING_CONNECT_SSH_N"
    fi
}
